<?php
/*
 * help.php
 *
 * part of Firew4LL (https://www.firew4ll.com)
 * Copyright (c) 2020 InSecureNet, SRL (ISN)
 * 
 * forked from pfSense (https://www.pfsense.org)
 * Copyright (c) 2004-2019 Rubicon Communications, LLC (Netgate)
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

require_once("guiconfig.inc");

/* Define hash of jumpto url maps */
$helppages = array(
	'index.php' => 'http://doc.firew4ll.com/it/latest/',

	'crash_reporter.php' => 'http://doc.firew4ll.com/',
	'diag_arp.php' => 'http://doc.firew4ll.com/it/latest/guidamenu/index.html?highlight=tabella%20arp#diagnostica',
	'diag_authentication.php' => 'http://doc.firew4ll.com/it/latest/utenti/index.html?highlight=autenticazione',
	'diag_backup.php' => 'http://doc.firew4ll.com/it/latest/backup/index.html',
	'diag_command.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'diag_confbak.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html#ripristino-della-configurazione-recente',
	'diag_defaults.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html#ripristino-delle-impostazioni-di-fabbrica',
	'diag_dns.php' => 'http://doc.firew4ll.com/it/latest/multiwan/index.html?highlight=Dns%20Lookup#dns-forwarder',
	'diag_dump_states.php' => 'http://doc.firew4ll.com/it/latest/guidamenu/index.html?highlight=mostra%20stati#diagnostica',
	'diag_dump_states_sources.php' => 'http://doc.firew4ll.com/it/latest/guidamenu/index.html?highlight=mostra%20stati#diagnostica',
	'diag_edit.php' => 'http://doc.firew4ll.com/it/latest/',
	'diag_gmirror.php' => 'http://doc.firew4ll.com/it/latest/installagg/index.html',
	'diag_halt.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html?#arresta-il-sistema',
	'diag_limiter_info.php' => 'http://doc.firew4ll.com/it/latest/trafficoshaper/index.html?highlight=limitatore#traffic-shaper',
	'diag_ndp.php' => 'http://doc.firew4ll.com/it/latest/rete/index.html?highlight=ndp#ndp-neighbor-discovery-protocol',
	'diag_packet_capture.php' => 'http://doc.firew4ll.com/it/latest/introduzione/index.html?highlight=sniffer#dispositivo-sniffer',
	'diag_pf_info.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html#installazione-dei-pacchetti',
	'diag_pftop.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html?highlight=pftop#pftop',
	'diag_ping.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html?highlight=ping#ping-host',
	'diag_reboot.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html?highlight=ping#riavvio-del-sistema',
	'diag_resetstate.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html?highlight=ping#riavviare-webconfigurator',
	'diag_routes.php' => 'http://doc.firew4ll.com/it/latest/routing/index.html?highlight=route#visualizzazione-delle-rotte',
	'diag_smart.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?highlight=smart#salute',
	'diag_sockets.php' => 'http://doc.firew4ll.com/it/latest',
	'diag_states_summary.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=tabelle#tabelle-di-stato',
	'diag_system_activity.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#attivita-sistema-top',
	'diag_tables.php' => 'http://doc.firew4ll.com/it/latest/routing/index.html',
	'diag_testport.php' => 'http://doc.firew4ll.com/it/latest/routing/index.html',
	'diag_traceroute.php' => 'http://doc.firew4ll.com/it/latest/routing/index.html?highlight=traceroute#utilizzare-traceroute',
	'easyrule.php' => 'http://doc.firew4ll.com/it/latest/firewall/index.html?#l-aggiunta-di-regole-firewall-dalla-vista-del-registro-regola-semplice-easy-rule',
	'firewall_aliases_edit.php' => 'http://doc.firew4ll.com/it/latest/firewall/index.html?#alias',
	'firewall_aliases_import.php' => 'http://doc.firew4ll.com/it/latest/firewall/index.html?#alias',
	'firewall_aliases.php' => 'http://doc.firew4ll.com/it/latest/firewall/index.html?#alias',
	'firewall_nat_1to1_edit.php' => 'http://doc.firew4ll.com/it/latest/nat/index.html#nat-1:1',
	'firewall_nat_1to1.php' => 'http://doc.firew4ll.com/it/latest/nat/index.html#nat-1:1',
	'firewall_nat_edit.php' => 'http://doc.firew4ll.com/it/latest/nat/index.html#porte-dinoltro-port-forward',
	'firewall_nat_npt_edit.php' => 'http://doc.firew4ll.com/it/latest/nat/index.html#traduzione-dei-prefissi-di-rete-ipv6-npt',
	'firewall_nat_npt.php' => 'http://doc.firew4ll.com/it/latest/nat/index.html#traduzione-dei-prefissi-di-rete-ipv6-npt',
	'firewall_nat_out_edit.php' => 'http://doc.firew4ll.com/it/latest/nat/index.html#nat-in-uscita',
	'firewall_nat_out.php' => 'http://doc.firew4ll.com/it/latest/nat/index.html#nat-in-uscita',
	'firewall_nat.php' => 'http://doc.firew4ll.com/it/latest/nat/index.html#porte-dinoltro-port-forward',
	'firewall_rules_edit.php' => 'http://doc.firew4ll.com/it/latest/firewall/index.html',
	'firewall_rules.php' => 'http://doc.firew4ll.com/it/latest/firewall/index.html',
	'firewall_schedule_edit.php' => 'http://doc.firew4ll.com/it/latest/firewall/index.html?#usare-la-pianificazione-in-una-regola-del-firewall',
	'firewall_schedule.php' => 'http://doc.firew4ll.com/it/latest/firewall/index.html?#usare-la-pianificazione-in-una-regola-del-firewall',
	'firewall_shaper.php' => 'http://doc.firew4ll.com/it/latest/trafficoshaper/index.html?',
	'firewall_shaper_queues.php' => 'http://doc.firew4ll.com/it/latest/trafficoshaper/index.html?',
	'firewall_shaper_vinterface.php' => 'http://doc.firew4ll.com/it/latest/trafficoshaper/index.html?#limitatori',
	'firewall_shaper_wizards.php' => 'http://doc.firew4ll.com/it/latest/trafficoshaper/index.html?',
	'firewall_virtual_ip_edit.php' => 'http://doc.firew4ll.com/it/latest/firewall/index.html#indirizzi-ip-virtuali-vip',
	'firewall_virtual_ip.php' => 'http://doc.firew4ll.com/it/latest/firewall/index.html#indirizzi-ip-virtuali-vip',
	'interfaces_assign.php' => 'http://doc.firew4ll.com/it/latest/installagg/index.html#assegnamento-interfacce',
	'interfaces_bridge_edit.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#bridge',
	'interfaces_bridge.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#bridge',
	'interfaces_gif_edit.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#gif-interfaccia-di-tunnel-generica',
	'interfaces_gif.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#gif-interfaccia-di-tunnel-generica',
	'interfaces_gre_edit.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#gre-incapsulamento-del-routing-generico',
	'interfaces_gre.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#gre-incapsulamento-del-routing-generico',
	'interfaces_groups_edit.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#gruppo-di-interfacce',
	'interfaces_groups.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#gruppo-di-interfacce',
	'interfaces_lagg_edit.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#lagg-aggregazione-di-link',
	'interfaces_lagg.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#lagg-aggregazione-di-link',
	'interfaces.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html',
	'interfaces_ppps_edit.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#ppp',
	'interfaces_ppps.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#ppp',
	'interfaces_qinq_edit.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#qinq',
	'interfaces_qinq.php' => 'http://doc.firew4ll.com/it/latest/interfacce/index.html#qinq',
	'interfaces_vlan_edit.php' => 'http://doc.firew4ll.com/it/latest/vlan/index.html',
	'interfaces_vlan.php' => 'http://doc.firew4ll.com/it/latest/vlan/index.html',
	'interfaces_wireless_edit.php' => 'http://doc.firew4ll.com/it/latest/wireless/index.html',
	'interfaces_wireless.php' => 'http://doc.firew4ll.com/it/latest/wireless/index.html',
	'load_balancer_monitor_edit.php' => 'http://doc.firew4ll.com/it/latest/bilanciamento/index.html',
	'load_balancer_monitor.php' => 'http://doc.firew4ll.com/it/latest/bilanciamento/index.html',
	'load_balancer_pool_edit.php' => 'http://doc.firew4ll.com/it/latest/bilanciamento/index.html',
	'load_balancer_pool.php' => 'http://doc.firew4ll.com/it/latest/bilanciamento/index.html',
	'load_balancer_setting.php' => 'http://doc.firew4ll.com/it/latest/bilanciamento/index.html',
	'load_balancer_virtual_server_edit.php' => 'http://doc.firew4ll.com/it/latest/bilanciamento/index.html',
	'load_balancer_virtual_server.php' => 'http://doc.firew4ll.com/it/latest/bilanciamento/index.html',
	'miniupnpd.xml' => 'http://doc.firew4ll.com/it/latest/servizi/index.html?#upnp-e-nat-pmp',
	'openvpn-client-export.xml' => 'http://doc.firew4ll.com/it/latest/vpn/openvpn/index.html#installazione-del-client-di-openvpn', /* Package */
	'pkg_mgr_installed.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'pkg_mgr_install.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'pkg_mgr.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'services_captiveportal_filemanager.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_captiveportal_hostname_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_captiveportal_hostname.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_captiveportal_ip_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_captiveportal_ip.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_captiveportal_mac_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_captiveportal_mac.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_captiveportal.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_captiveportal_vouchers_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_captiveportal_vouchers.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_captiveportal_zones_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_captiveportal_zones.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_checkip_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_checkip.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html',
	'services_dhcp_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#server-dhcp-ipv4',
	'services_dhcp.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#server-dhcp-ipv4',
	'services_dhcp_relay.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#annunci-del-router-e-server-dhcp-con-ipv6',
	'services_dhcpv6_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#annunci-del-router-e-server-dhcp-con-ipv6',
	'services_dhcpv6.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#annunci-del-router-e-server-dhcp-con-ipv6',
	'services_dhcpv6_relay.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#annunci-del-router-e-server-dhcp-con-ipv6',
	'services_dnsmasq_domainoverride_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html?#configurazione-del-forwarder-del-dns',
	'services_dnsmasq_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html?highlight=dnsmasq#configurazione-del-forwarder-del-dns',
	'services_dnsmasq.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html?highlight=dnsmasq#configurazione-del-forwarder-del-dns',
	'services_dyndns_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#id1',
	'services_dyndns.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#id1',
	'services_igmpproxy_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#proxy-igmp',
	'services_igmpproxy.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#proxy-igmp',
	'services_ntpd_acls.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#ntpd',
	'services_ntpd_gps.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#ntpd',
	'services_ntpd.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#ntpd',
	'services_ntpd_pps.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#ntpd',
	'services_pppoe_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#server-pppoe',
	'services_pppoe.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#server-pppoe',
	'services_rfc2136_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html?#dns-dinamico',
	'services_rfc2136.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html?#dns-dinamico',
	'services_router_advertisements.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#annunci-del-router-o-dove-l-opzione-del-gateway-dhcpv6',
	'services_snmp.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#snmp',
	'services_unbound_acls.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#risolutore-dns',
	'services_unbound_advanced.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#risolutore-dns',
	'services_unbound_domainoverride_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#risolutore-dns',
	'services_unbound_host_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#risolutore-dns',
	'services_unbound.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#risolutore-dns',
	'services_wol_edit.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#wol-wake-on-lan',
	'services_wol.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html#wol-wake-on-lan',
	'status_captiveportal_expire.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#captive-portal',
	'status_captiveportal.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#captive-portal',
	'status_captiveportal_test.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#captive-portal',
	'status_captiveportal_voucher_rolls.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#captive-portal',
	'status_captiveportal_vouchers.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#captive-portal',
	'status_carp.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#stato-del-carp',
	'status_dhcp_leases.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#dhcp',
	'status_dhcpv6_leases.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#dhcp',
	'status_filter_reload.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html?#filtri-log',
	'status_gateway_groups.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#gateway',
	'status_gateways.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#gateway',
	'status_graph_cpu.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#grafici-di-monitoraggio',
	'status_graph.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#grafici-di-monitoraggio',
	'status_interfaces.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#stato-dellinterfaccia',
	'status_ipsec_leases.php' => 'http://doc.firew4ll.com/it/latest/vpn/ipsec/index.html',
	'status_ipsec.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#ipsec',
	'status_ipsec_sad.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#ipsec',
	'status_ipsec_spd.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?#ipsec',
	'status_lb_pool.php' => 'http://doc.firew4ll.com/it/latest/bilanciamento/index.html',
	'status_lb_vs.php' => 'http://doc.firew4ll.com/it/latest/bilanciamento/index.html',
	'status_logs_filter_dynamic.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs_filter.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs_filter_summary.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php-dhcpd' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php-gateways' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php-ipsec' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php-ntpd' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php-openvpn' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php-portalauth' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php-ppp' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php-relayd' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php-resolver' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php-routing' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs.php-wireless' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs_settings.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_logs_vpn.php' => 'http://doc.firew4ll.com/it/latest/vpn/openvpn/index.html',
	'status_ntpd.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html?#server-ntp',
	'status_openvpn.php' => 'http://doc.firew4ll.com/it/latest/vpn/openvpn/index.html',
	'status_pkglogs.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_queues.php' => 'http://doc.firew4ll.com/it/latest/trafficoshaper/index.html?',
	'status_services.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html?',
	'status_upnp.php' => 'http://doc.firew4ll.com/it/latest/servizi/index.html?#upnp-e-nat-pmp',
	'status_wireless.php' => 'http://doc.firew4ll.com/it/latest/wireless/index.html',
	'system_advanced_admin.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html#opzioni-configurazione-avanzata',
	'system_advanced_firewall.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html#opzioni-configurazione-avanzata',
	'system_advanced_misc.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html#opzioni-configurazione-avanzata',
	'system_advanced_network.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html#opzioni-configurazione-avanzata',
	'system_advanced_notifications.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html#opzioni-configurazione-avanzata',
	'system_advanced_sysctl.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html#opzioni-configurazione-avanzata',
	'system_authservers.php' => 'http://doc.firew4ll.com/it/latest/utenti/index.html',
	'system_camanager.php' => 'http://doc.firew4ll.com/it/latest/certificati/index.html',
	'system_certmanager.php' => 'http://doc.firew4ll.com/it/latest/certificati/index.html',
	'system_crlmanager.php' => 'http://doc.firew4ll.com/it/latest/certificati/index.html',
	'system_gateway_groups_edit.php' => 'http://doc.firew4ll.com/it/latest/routing/index.html?#gateway',
	'system_gateway_groups.php' => 'http://doc.firew4ll.com/it/latest/routing/index.html?#gateway',
	'system_gateways_edit.php' => 'http://doc.firew4ll.com/it/latest/routing/index.html?#gateway',
	'system_gateways.php' => 'http://doc.firew4ll.com/it/latest/routing/index.html?#gateway',
	'system_groupmanager_addprivs.php' => 'http://doc.firew4ll.com/it/latest/utenti/index.html?#aggiunta-modifica-dei-gruppi',
	'system_groupmanager.php' => 'http://doc.firew4ll.com/it/latest/utenti/index.html?#aggiunta-modifica-dei-gruppi',
	'system_hasync.php' => 'http://doc.firew4ll.com/it/latest/ha/index.html',
	'system.php' => 'http://doc.firew4ll.com/it/latest/configurazione/index.html?#opzioni-configurazione-generale',
	'system_routes_edit.php' => 'http://doc.firew4ll.com/it/latest/routing/index.html?#rotte-statiche',
	'system_routes.php' => 'http://doc.firew4ll.com/it/latest/routing/index.html?#rotte-statiche',
	'system_update_settings.php' => 'http://doc.firew4ll.com/it/latest/installagg/index.html?highlight=firmware#aggiornamento',
	'system_usermanager_addprivs.php' => 'http://doc.firew4ll.com/it/latest/utenti/index.html',
	'system_usermanager_passwordmg.php' => 'http://doc.firew4ll.com/it/latest/utenti/index.html',
	'system_usermanager.php' => 'http://doc.firew4ll.com/it/latest/utenti/index.html',
	'system_usermanager_settings.php' => 'http://doc.firew4ll.com/it/latest/utenti/index.html',
	'system_user_settings.php' => 'http://doc.firew4ll.com/it/latest/utenti/index.html',
	'vpn_ipsec_keys_edit.php' => 'http://doc.firew4ll.com/it/latest/vpn/ipsec/index.html',
	'vpn_ipsec_keys.php' => 'http://doc.firew4ll.com/it/latest/vpn/ipsec/index.html',
	'vpn_ipsec_mobile.php' => 'http://doc.firew4ll.com/it/latest/vpn/ipsec/index.html',
	'vpn_ipsec_phase1.php' => 'http://doc.firew4ll.com/it/latest/vpn/ipsec/index.html',
	'vpn_ipsec_phase2.php' => 'http://doc.firew4ll.com/it/latest/vpn/ipsec/index.html',
	'vpn_ipsec.php' => 'http://doc.firew4ll.com/it/latest/vpn/ipsec/index.html',
	'vpn_ipsec_settings.php' => 'http://doc.firew4ll.com/it/latest/vpn/ipsec/index.html',
	'vpn_l2tp.php' => 'http://doc.firew4ll.com/it/latest/vpn/l2tp/index.html',
	'vpn_l2tp_users_edit.php' => 'http://doc.firew4ll.com/it/latest/vpn/l2tp/index.html',
	'vpn_l2tp_users.php' => 'http://doc.firew4ll.com/it/latest/vpn/l2tp/index.html',
	'vpn_openvpn_client.php' => 'http://doc.firew4ll.com/it/latest/vpn/openvpn/index.html',
	'vpn_openvpn_csc.php' => 'http://doc.firew4ll.com/it/latest/vpn/openvpn/index.html',
	'vpn_openvpn_export.php' => 'http://doc.firew4ll.com/it/latest/vpn/openvpn/index.html', /* Package */
	'vpn_openvpn_export_shared.php' => 'http://doc.firew4ll.com/it/latest/vpn/openvpn/index.html', /* Package */
	'vpn_openvpn_server.php' => 'http://doc.firew4ll.com/it/latest/vpn/openvpn/index.html',

	/* Packages from here on down. Not checked as strictly. Pages may not yet exist. */
	'acme/acme_accountkeys_edit.php' => 'http://doc.firew4ll.com/it/latest/certificati/index.html',
	'acme/acme_accountkeys.php' => 'http://doc.firew4ll.com/it/latest/certificati/index.html',
	'acme/acme_certificates_edit.php' => 'http://doc.firew4ll.com/it/latest/certificati/index.html',
	'acme/acme_certificates.php' => 'http://doc.firew4ll.com/it/latest/certificati/index.html',
	'acme/acme_generalsettings.php' => 'http://doc.firew4ll.com/it/latest/certificati/index.html',
	'acme.xml' => 'http://doc.firew4ll.com/it/latest/certificati/index.html',
	'apcupsd_status.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'apcupsd.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'arping.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'autoconfigbackup_backup.php' => 'http://doc.firew4ll.com/it/latest/backup/index.html',
	'autoconfigbackup.php' => 'http://doc.firew4ll.com/it/latest/backup/index.html',
	'autoconfigbackup_stats.php' => 'http://doc.firew4ll.com/it/latest/backup/index.html',
	'autoconfigbackup.xml' => 'http://doc.firew4ll.com/it/latest/backup/index.html',
	'avahi.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'backup.xml' => 'http://doc.firew4ll.com/it/latest/backup/index.html',
	'bind_acls.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=bind#configurare-il-server-bind',
	'bind_sync.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=bind#configurare-il-server-bind',
	'bind_views.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=bind#configurare-il-server-bind',
	'bind.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=bind#configurare-il-server-bind',
	'bind_zones.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=bind#configurare-il-server-bind',
	'blinkled.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'cellular.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'cron.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'darkstat.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'freeradiusauthorizedmacs.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'freeradiuscerts.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'freeradiusclients.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'freeradiuseapconf.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'freeradiusinterfaces.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'freeradiusmodulesldap.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'freeradiussettings.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'freeradiussqlconf.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'freeradiussync.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'freeradius_view_config.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'freeradius.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'ftpproxy.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'gwled.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'gwled.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'haproxy/haproxy_files.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'haproxy/haproxy_global.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'haproxy/haproxy_listeners_edit.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'haproxy/haproxy_listeners.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'haproxy/haproxy_pool_edit.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'haproxy/haproxy_pools.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'haproxy/haproxy_stats.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'haproxy/haproxy_templates.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'haproxy.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'iftop.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=iftop',
	'iperfserver.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=iftop',
	'iperf.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=iftop',
	'ladvd.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=iftop',
	'lcdproc.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=iftop',
	'lightsquid.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=iftop',
	'mailreport.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=iftop',
	'mtr-nox11.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?highlight=iftop',
	'net-snmp_communities.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?',
	'net-snmptrapd_communities.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?',
	'net-snmptrapd_formats.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?',
	'net-snmptrapd_forwards.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?',
	'net-snmptrapd_traphandles.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?',
	'net-snmptrapd_users.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?',
	'net-snmptrapd.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?',
	'net-snmp_trapgen.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?',
	'net-snmp_users.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?',
	'net-snmp.xml' => 'http://doc.firew4ll.com/it/latest/software3parti/index.html?',
	'nmap.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'notes.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'nrpe.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'ntopng.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'nut_settings.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'nut_status.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'nut.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'openbgpd_groups.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'openbgpd_neighbors.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'openbgpd_raw.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'openbgpd_status.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'openbgpd.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'open-vm-tools.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'packages/backup/backup_edit.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'packages/backup/backup.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'packages/cron/cron_edit.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'packages/cron/cron.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'packages/cron/index.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'packages/lcdproc/index.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'packages/lcdproc/lcdproc.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'packages/lcdproc/lcdproc_screens.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng_alerts_ar.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng_alerts.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng_dnsbl_easylist.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng_dnsbl_lists.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng_dnsbl.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng_log.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng_sync.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng_threats.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng_update.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng_v4lists.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/pfblockerng_v6lists.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng/www/index.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'pfblockerng.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=cron#introduzione-ai-pacchetti',
	'quagga_ospfd_interfaces.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'quagga_ospfd_raw.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'quagga_ospfd.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'routed.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html', # RIP
	'services_servicewatchdog_add.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'services_servicewatchdog.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'servicewatchdog.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'shellcmd.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'siproxd_registered_phones.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'siproxdusers.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'siproxd.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html',
	'snort/snort_alerts.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_barnyard.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_blocked.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_define_servers.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_download_rules.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_download_updates.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_edit_hat_data.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_frag3_engine.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_ftp_client_engine.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_ftp_server_engine.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_httpinspect_engine.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_import_aliases.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_interface_logs.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_interfaces_edit.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_interfaces_global.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_interfaces.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_interfaces_suppress_edit.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_interfaces_suppress.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_ip_list_mgmt.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_iprep_list_browser.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_ip_reputation.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_list_view.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_log_mgmt.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_passlist_edit.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_passlist.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_preprocessors.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_rules_edit.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_rulesets.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricataets',
	'snort/snort_rules_flowbits.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_rules.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_select_alias.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_sid_mgmt.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_stream5_engine.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort/snort_sync.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'snort.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=snort#snort-suricata',
	'softflowd.xml' => 'https://github.com/irino/softflowd',
	'sqstat/sqstat.class.php' => 'http://samm.kiev.ua/sqstat/',
	'sqstat/sqstat.php' => 'http://samm.kiev.ua/sqstat/',
	'squid_antivirus.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_auth.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_cache.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squidguard_acl.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=squidguard#squidguard-controllo-e-filtro-dell-accesso-web',
	'squidguard_default.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=squidguard#squidguard-controllo-e-filtro-dell-accesso-web',
	'squidguard_dest.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=squidguard#squidguard-controllo-e-filtro-dell-accesso-web',
	'squidguard_rewr.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=squidguard#squidguard-controllo-e-filtro-dell-accesso-web',
	'squidGuard/squidguard_blacklist.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=squidguard#squidguard-controllo-e-filtro-dell-accesso-web',
	'squidGuard/squidguard_log.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=squidguard#squidguard-controllo-e-filtro-dell-accesso-web',
	'squidguard_sync.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=squidguard#squidguard-controllo-e-filtro-dell-accesso-web',
	'squidguard_time.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=squidguard#squidguard-controllo-e-filtro-dell-accesso-web',
	'squidguard.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=squidguard#squidguard-controllo-e-filtro-dell-accesso-web',
	'squidguard.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=squidguard#squidguard-controllo-e-filtro-dell-accesso-web',
	'squid_log_parser.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_monitor_data.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_monitor.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_reverse_general.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_reverse_peer.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_reverse_redir.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_reverse_sync.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_reverse_uri.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_sync.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_traffic.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_upstream.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid_users.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'squid.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=squid#squid',
	'status_ladvd.php' => 'https://github.com/sspans/ladvd',
	'status_mail_report_add_cmd.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html#installazione-dei-pacchetti',
	'status_mail_report_add_log.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html#installazione-dei-pacchetti',
	'status_mail_report_edit.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html#installazione-dei-pacchetti',
	'status_mail_report.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html#installazione-dei-pacchetti',
	'status_ospfd.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_tinc.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html',
	'status_traffic_totals.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?highlight=monitoraggio%20traffico#id1',
	'stunnel_certs.xml' => 'https://www.stunnel.org/docs.html',
	'stunnel.xml' => 'https://www.stunnel.org/docs.html',
	'sudo.xml' => 'http://doc.firew4ll.com/it/latest/utenti/index.html?highlight=sudo#privilegi',
	'suricata/suricata_alerts.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_app_parsers.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_barnyard.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_blocked.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_define_vars.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_download_rules.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_download_updates.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_flow_stream.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_global.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_import_aliases.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_interfaces_edit.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_interfaces.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_ip_list_mgmt.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_iprep_list_browser.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_ip_reputation.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_libhtp_policy_engine.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_list_view.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_logs_browser.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_logs_mgmt.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_os_policy_engine.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_passlist_edit.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_passlist.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_rules_edit.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_rulesets.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_rules_flowbits.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_rules.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_select_alias.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_sid_mgmt.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_suppress_edit.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_suppress.php' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata/suricata_sync.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'suricata.xml' => 'http://doc.firew4ll.com/it/latest/hardware/index.html?highlight=suricata#snort-suricata',
	'syslog-ng_advanced.xml' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?highlight=syslog',
	'syslog-ng_log_viewer.php' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?highlight=syslog',
	'syslog-ng.xml' => 'http://doc.firew4ll.com/it/latest/monitoraggio/index.html?highlight=syslog',
	'system_patches_edit.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=pacchetti',
	'system_patches.php' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=pacchetti',
	'systempatches.xml' => 'https://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=pacchetti',
	'tftpd.xml' => 'http://doc.firew4ll.com/it/latest/nat/index.html?highlight=tftp#tftp',
	'tftp_files.php' => 'http://doc.firew4ll.com/it/latest/nat/index.html?highlight=tftp#tftp',
	'tinc_hosts.xml' => 'https://tinc-vpn.org/docs/',
	'tinc.xml' => 'https://tinc-vpn.org/docs/',
	'vpc_vpn_wizard.xml' => 'http://doc.firew4ll.com/it/latest/vpn/index.html',
	'zabbix-agent-lts.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=zabbix#introduzione-ai-pacchetti',
	'zabbix-proxy-lts.xml' => 'http://doc.firew4ll.com/it/latest/pacchetti/index.html?highlight=zabbix#introduzione-ai-pacchetti',
);

$pagename = "";
/* Check for parameter "page". */
if ($_REQUEST && isset($_REQUEST['page'])) {
	$pagename = $_REQUEST['page'];
}

/* If "page" is not found, check referring URL */
if (empty($pagename)) {
	/* Attempt to parse out filename */
	$uri_split = "";
	preg_match("/\/(.*)\?(.*)/", $_SERVER["HTTP_REFERER"], $uri_split);

	/* If there was no match, there were no parameters, just grab the filename
		Otherwise, use the matched filename from above. */
	if (empty($uri_split[0])) {
		$pagename = ltrim(parse_url($_SERVER["HTTP_REFERER"], PHP_URL_PATH), '/');
	} else {
		$pagename = $uri_split[1];
	}

	/* If the referrer was index.php then this was a redirect to help.php
	   because help.php was the first page the user has priv to.
	   In that case we do not want to redirect off to the dashboard help. */
	if ($pagename == "index.php") {
		$pagename = "";
	}

	/* If the filename is pkg_edit.php or wizard.php, reparse looking
		for the .xml filename */
	if (($pagename == "pkg.php") || ($pagename == "pkg_edit.php") || ($pagename == "wizard.php")) {
		$param_split = explode('&', $uri_split[2]);
		foreach ($param_split as $param) {
			if (substr($param, 0, 4) == "xml=") {
				$xmlfile = explode('=', $param);
				$pagename = $xmlfile[1];
			}
		}
	}
}

/* Using the derived page name, attempt to find in the URL mapping hash */
if (strlen($pagename) > 0) {
	if (array_key_exists($pagename, $helppages)) {
		$helppage = $helppages[$pagename];
	} else {
		// If no specific page was found, use a generic help page
		$helppage = 'http://doc.firew4ll.com/it/latest/';
	}

	/* Redirect to help page. */
	header("Location: {$helppage}");
}

// No page name was determined, so show a message.
$pgtitle = array(gettext("Help"), gettext("About this Page"));
require_once("head.inc");

if (is_array($allowedpages) && str_replace('*', '', $allowedpages[0]) == "help.php") {
	if (count($allowedpages) == 1) {
		print_info_box(gettext("The Help page is the only page this user has privilege for."));
	} else {
		print_info_box(gettext("Displaying the Help page because it is the first page this user has privilege for."));
	}
} else {
	print_info_box(gettext("Help page accessed directly without any page parameter."));
}

include("foot.inc");
?>
